### PR TITLE
49 change request chapter 1 needs more pictures

### PR DESCRIPTION
**Pull request by dsmits**

### CODE REVIEW

**Review by frankcorneliusmartin — COMMENTED** [review]
* In the federated analytics example I think we should extend the figure caption a little to also mention that this *can* be an iterative process. I understand that it would clutter the figure to much to add it in there. Or am I mistaken and do we consider this to be Federated *Learning* in this case?
* In the federated learning example we are *always* dealing with multiple rounds as we are really sharing the gradient to find an optimal solution. Maybe we can have a second arrow pointing back with something like 'weights'.
* I think the caption of the gradient leakage might be a bit more elaborative. As it also seems to mee the Ground truth row is incorrect? 
* In the secure multiparty example I do not understand why there are only two data partners. I would expect that the third party would also contribute a share. Maybe add a small dataset to the right building as well?
* The differential privacy image is too heavily focused on the analytics part. I would just show a small data set before and after applying differential privacy. Also 
  
  >  replace a selection of inputs with random noise
  
  I don't think it necessarily is just a selection, same for: 
  
  > Differential privacy replaces a subset of the data with random values

**Comment by dsmits** [comment]
@frankcorneliusmartin: Integrated all your comments except for the last one because I don't agree

**Comment by frankcorneliusmartin** [comment]
I am unfamiliar with DP. However I've seen our implementation for our breast cancer dataset. I think the case you are referring to is when you use Boolean values (the flipping coin process). Which makes sense as you cannot add noise to Boolean values. You can only flip a subset of your data, so you obtain plausible 

In case you have real numbers you do add noise (Laplacian or Gaussian) to each individual record, see for example: https://desfontain.es/blog/differential-privacy-in-practice.html. There is the exception that the random sample from the Laplacian distribution is equal to zero. In that case you would indeed get the original value (but I would not call this a subset). 

I am also oke, by keeping this technique at a more high level description as -sorry if I am mistake- no one is an expert in this field from our group.

**Comment by dsmits** [comment]
Like we discussed, I'm going to merge this PR but I've opened another issue for the DP stuff: #77

**Pull request merged**
